### ISSUE TITLE
Publish VS Code extension

### ISSUE THREAD

**Issue by mtdowling** [awslabs/smithy-vscode#7]
We should actually publish the extension now that Smithy is GA. This extension still doesn't do much, but it would be easier to get syntax highlighting.

**Comment by jarruda** [comment]
+1 What's needed to do this? How can I help?

**Comment by srchase** [comment]
This extension can now be installed from the Marketplace: https://marketplace.visualstudio.com/items?itemName=Smithy.smithy-vscode-extension
